local catppuccin_ok, catppuccin = pcall(require, "catppuccin")

if catppuccin_ok then
	catppuccin.setup({
		flavour = "macchiato",
		transparent_background = false,
		show_end_of_buffer = false,
		dim_inactive = {
			enabled = false,
			shade = "dark",
			percentage = 0.15,
		},
		no_italic = false,
		no_bold = false,
		no_underline = false,
		styles = {
			comments = { "italic" },
			conditionals = { "italic" },
			loops = {},
			functions = {},
			keywords = {},
			strings = {},
			variables = {},
			numbers = { "bold" },
			booleans = {},
			properties = {},
			types = {},
			operators = {},
		},
		color_overrides = {},
		custom_highlights = function(colors)
			return {
				CursorColumn = { bg = colors.surface0 },
				CursorLine = { bg = colors.surface0 },
				CursorLineNr = { fg = colors.text, bg = colors.surface1 },
				LineNr = { fg = colors.teal },
				LineNrAbove = { fg = colors.peach },
				NvimTreeWinSeparator = { bg = "none" },
				-- Navic --
				NavicSeparator = { fg = colors.green },
				NavicText = { fg = colors.subtext0 },
				NavicIconsFile = { fg = colors.blue },
				NavicIconsModule = { fg = colors.sapphire },
				NavicIconsNamespace = { fg = colors.lavender },
				NavicIconsPackage = { fg = colors.mauve },
				NavicIconsClass = { fg = colors.yellow },
				NavicIconsInterface = { fg = colors.peach },
				NavicIconsStruct = { fg = colors.flamingo },
				NavicIconsEnum = { fg = colors.red },
				NavicIconsEnumMemeber = { fg = colors.maroon },
				NavicIconsFunction = { fg = colors.green },
				NavicIconsMethod = { fg = colors.teal },
				NavicIconsConstructor = { fg = colors.sky },
				NavicIconsVariable = { fg = colors.text },
				NavicIconsConstant = { fg = colors.rosewater },
				NavicIconsProperty = { fg = colors.pink },
				NavicIconsField = { fg = colors.subtext1 },
				NavicIconsKey = { fg = colors.subtext0 },
				NavicIconsString = { fg = colors.green },
				NavicIconsNumber = { fg = colors.peach },
				NavicIconsBoolean = { fg = colors.mauve },
				NavicIconsArray = { fg = colors.yellow },
				NavicIconsObject = { fg = colors.blue },
				NavicIconsNull = { fg = colors.overlay0 },
				NavicIconsEvent = { fg = colors.red },
				NavicIconsOperator = { fg = colors.sky },
				NavicIconsTypeParameter = { fg = colors.lavender },
				-- Lualine custom highlights
				SLLanguageServer = { fg = colors.sapphire, bold = true },
				SLCopilot = { fg = colors.mauve, bold = true },
			}
		end,
		default_integrations = true,
		integrations = {
			cmp = true,
			gitsigns = true,
			treesitter = true,
			notify = true,
			mini = {
				enabled = true,
				indentscope_color = "",
			},
		},
		float = {
			enabled = true,
			max_with = nil,
			max_height = nil,
			border = "single",
			border_highlight = "FloatBorder",
			winblend = 0,
			transparent = true,
			solid = true,
		},
	})

	vim.cmd.colorscheme("catppuccin")
end
